# SPDX-FileCopyrightText: 2026 Luis Reis Viera
# SPDX-License-Identifier: Apache-2.0

# --- Usuario ---
USUARIO_NOMBRE = "username"
USUARIO_CONTRASENA_HASH = "hash"
USUARIO_ROL = "rol"

ROL_SUPERVISOR = "supervisor"
ROL_CAJERO = "cajero"

# --- Producto ---
PRODUCTO_CODIGO = "codigo"
PRODUCTO_NOMBRE = "nombre"
PRODUCTO_GRUPO = "grupo"
PRODUCTO_PRECIO = "precio"
PRODUCTO_STOCK = "stock"

ENCABEZADO_PRODUCTOS = [PRODUCTO_CODIGO, PRODUCTO_NOMBRE, PRODUCTO_GRUPO, PRODUCTO_PRECIO, PRODUCTO_STOCK]

# --- Venta ---
VENTA_FECHA_HORA = "fecha_hora"
VENTA_NRO_FACTURA = "nro_factura"
VENTA_USUARIO = "usuario"
VENTA_CODIGO = "codigo"
VENTA_CANTIDAD = "cantidad"
VENTA_PRECIO_UNIT = "precio_unit"
VENTA_SUBTOTAL = "subtotal"

ENCABEZADO_VENTAS = [
    VENTA_FECHA_HORA,
    VENTA_NRO_FACTURA,
    VENTA_USUARIO,
    VENTA_CODIGO,
    VENTA_CANTIDAD,
    VENTA_PRECIO_UNIT,
    VENTA_SUBTOTAL,
]

# --- Cierre diario ---
CIERRE_FECHA = "fecha"
CIERRE_TOTAL_VENTAS = "total_ventas"
CIERRE_TOTAL_UNIDADES = "total_unidades"
CIERRE_IMPORTE_TOTAL = "importe_total"

ENCABEZADO_CIERRE = [
    CIERRE_FECHA,
    CIERRE_TOTAL_VENTAS,
    CIERRE_TOTAL_UNIDADES,
    CIERRE_IMPORTE_TOTAL,
]
